### ISSUE TITLE
Script freezes

### ISSUE THREAD

**Issue by AndySAnker** [JunlinHan/DCLGAN#3]
Thanks for making this project open access and sharing the code in a nice format. I sincerely appreciate it!

I am running the code on an HPC server. Here I face the problem that the script freezes after 4-20 epochs. I do not receive any error messages and the HPC server does not terminate my script (which it usually does if for example if there is not enough  RAM allocated). The job is still active on the server but I can see from the log file that no more epochs are done. It has frozen. 
I have also tried to follow the RAM usage through training and I have not found any memory leak during training.

I am not sure if this problem is in the code or it is related to the HPC server. Have you encountered similar problems?

**Comment by JunlinHan** [comment]
Hi AndyNano,
I haven't meet such situations before, but you may refer to this issue: 
https://github.com/junyanz/pytorch-CycleGAN-and-pix2pix/issues/619
The solution discussed there is to disable visdom, also, adding --no_html might help.
